### ISSUE TITLE
Not logging in smf

### ISSUE THREAD

**Issue by saurabh1938** [oneall/social-login-simple-machines-forum#1]
I have installed social login. It has worked in the past.

But now I am not able to login using this. Users just redirect to forum page but don't get logged in.

my site is www.gotripperz.com

Please help me as I am losing much members because of this because few of my members use just this medium to login to my site

**Comment by SchlesserClaude** [comment]
Hello,

could you please open the Social Login settings in your SMF admin area
and click on the “Autodetect” and “Verify” buttons.

Please make sure that you get two green success messages,

Regards,

**Comment by saurabh1938** [comment]
Hi Thanks for the quick response.

I clicked on both and both showing Green. It has been detected and updated successfully.

**Comment by saurabh1938** [comment]
Anybody some thoughts... i am loosing members as those used to login using your mod

**Comment by SchlesserClaude** [comment]
Seems to work now ;) Closing the issue.

**Comment by saurabh1938** [comment]
hahaha... I still have unsolved queries.. anyways... thanks for your first response ;)
